### ISSUE TITLE
hello,how can i use it in windows 10?

### ISSUE THREAD

**Issue by fangkaiyu** [sam-ke/idCardOcr#1]
a error ,how to solve it ,could you give me a demo to show the way to use it in windows ?
![capture](https://user-images.githubusercontent.com/41827241/44296790-ee186c80-a2f7-11e8-9d52-18d109c59158.PNG)

**Comment by fangkaiyu** [comment]
ocr  图片名称
ocr  图片 图片路径  都有错误。你能演示一下windows系统下该如何使用吗

**Comment by sam-ke** [comment]
@fangkaiyu    Firstly ,I am so sorry to you，It’s been a long time before I reply to you.
idCardOcr need library tesseract, so  you must install it and its chinese Font library （chi_sim.traineddata）.
Ohter check list
1. I was installed 'tesseract' through this document, https://github.com/tesseract-ocr/tesseract
2. Use absolute path to the value of the ocr parameter image instead， 
eg:   ./ocr   "D:\path_to_your_imag_dir\1.jpg"
